name:                advent2021
version:             0.1.0.0
github:              "ehigham/advent"
license:             MIT
author:              "Edmund Higham"
maintainer:          "edhigham@gmail.com"
copyright:           "2021 Edmund Higham"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ehigham/advent/blob/main/2021/README.md>

ghc-options:
  - -Weverything
  - -Wno-missing-local-signatures
  - -Wno-missing-import-lists
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-missing-safe-haskell-mode
  - -Wno-implicit-prelude
  - -Wno-prepositive-qualified-module
  - -Werror
  - -O2

default-extensions:
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - FlexibleContexts
  - LambdaCase
  - RankNTypes
  - RecordWildCards
  - TupleSections

dependencies:
  - array
  - base >= 4.7 && < 5
  - Boolean
  - containers
  - hashable
  - mtl
  - split
  - Stack
  - unordered-containers
  - vector

library:
  source-dirs: src

executables:
  sonarsweep1:
    main:                Day1/part1.hs
    source-dirs:         src

  sonarsweep2:
    main:                Day1/part2.hs
    source-dirs:         src

  dive1:
    main:                Day2/part1.hs
    source-dirs:         src

  dive2:
    main:                Day2/part2.hs
    source-dirs:         src

  binarydiagnostic1:
    main:                Day3/part1.hs
    source-dirs:         src

  binarydiagnostic2:
    main:                Day3/part2.hs
    source-dirs:         src

  bingo1:
    main:                Day4/part1.hs
    source-dirs:         src

  bingo2:
    main:                Day4/part2.hs
    source-dirs:         src

  vents1:
    main:                Day5/part1.hs
    source-dirs:         src

  vents2:
    main:                Day5/part2.hs
    source-dirs:         src

  lanternfish1:
    main:                Day6/part1.hs
    source-dirs:         src

  lanternfish2:
    main:                Day6/part2.hs
    source-dirs:         src

  crabs1:
    main:                Day7/part1.hs
    source-dirs:         src

  crabs2:
    main:                Day7/part2.hs
    source-dirs:         src

  segment1:
    main:                Day8/part1.hs
    source-dirs:         src

  smoke1:
    main:                Day9/part1.hs
    source-dirs:         src

  smoke2:
    main:                Day9/part2.hs
    source-dirs:         src

  syntax1:
    main:                Day10/part1.hs
    source-dirs:         src

  syntax2:
    main:                Day10/part2.hs
    source-dirs:         src

  octopus1:
    main:                Day11/part1.hs
    source-dirs:         src

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -Wno-all-missed-specialisations
      - -Wno-unused-packages
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - advent2021
      - tasty
      - tasty-hunit

benchmarks:
  baselines:
    main:                Baselines.hs
    source-dirs:         bench
    ghc-options:
      - -Wno-unused-packages
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - advent2021
      - criterion
