name:                advent2021
version:             0.1.0.0
github:              "ehigham/advent"
license:             MIT
author:              "Edmund Higham"
maintainer:          "edhigham@gmail.com"
copyright:           "2021 Edmund Higham"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ehigham/advent/blob/main/2021/README.md>

ghc-options:
  - -Weverything
  - -Wno-missing-local-signatures
  - -Wno-missing-import-lists
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-missing-safe-haskell-mode
  - -Wno-implicit-prelude
  - -Wno-prepositive-qualified-module
  - -Werror

default-extensions:
  - DerivingStrategies
  - RankNTypes
  - LambdaCase

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  sonarsweep1:
    main:                Day1/part1.hs
    source-dirs:         src
    ghc-options:
      - -O2

  sonarsweep2:
    main:                Day1/part2.hs
    source-dirs:         src
    ghc-options:
      - -O2

  dive1:
    main:                Day2/part1.hs
    source-dirs:         src
    ghc-options:
      - -O2

  dive2:
    main:                Day2/part2.hs
    source-dirs:         src
    ghc-options:
      - -O2

  binarydiagnostic1:
    main:                Day3/part1.hs
    source-dirs:         src
    ghc-options:
      - -O2

tests:
  unittest:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -O0
      - -g
      - -Wno-unsafe
    dependencies:
      - advent2021
      - tasty
      - tasty-hunit
